=== ieg-dhr/DigitaleEditorikDMGK/DMGK 9p XML schema/Geburtsbriefe.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="source">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="metadata"/>
        <xs:element ref="edition"/>
        <xs:element ref="content"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="metadata">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="archival_description"/>
        <xs:element ref="source_description"/>
        <xs:element ref="digital_surrogate"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- For archival descriptions in XML, see e.g. https://www.loc.gov/ead/ead3schema.html -->
  <xs:element name="archival_description">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.archival_description"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.archival_description">
    <xs:attribute name="ArchiveName" use="required"/>
    <xs:attribute name="ArchiveLocation" use="required"/>
    <xs:attribute name="Bestand" use="required"/>
    <xs:attribute name="Klassifikation" use="required"/>
    <xs:attribute name="Signatur" use="required"/>
  </xs:attributeGroup>
  <xs:element name="source_description">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.source_description"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.source_description">
    <xs:attribute name="source_ID" use="required"/>
    <xs:attribute name="related_object"/>
    <xs:attribute name="catalogue_record" use="required"/>
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Geburtsbrief"/>
          <xs:enumeration value="Lehrbrief"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="place" use="required"/>
    <xs:attribute name="date" use="required"/>
    <xs:attribute name="material_specifications"/>
    <xs:attribute name="seal">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="wax"/>
          <xs:enumeration value="printed"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <!-- Gyyyymmdd or Lyyyymmdd, no dots between numbers -->
  <!-- -reference to source ID of related transcription, in case of a letter with data on the verso side -->
  <!-- URL of individual record in the online catalogue -->
  <!-- Ausstellungsort -->
  <!-- dd-mm-yyyy -->
  <!-- Materialangaben -->
  <!-- angeheftet/ausgedruckt -->
  <!--  JG: still not sure, should it be part of visual elements or new element entirely? And should we mention it's material, e.g. paper or wax? Is implied now -->
  <xs:element name="digital_surrogate">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.digital_surrogate"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.digital_surrogate">
    <xs:attribute name="filename"/>
    <xs:attribute name="URL"/>
  </xs:attributeGroup>
  <xs:element name="edition">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="transcription_info"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="editors"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="transcription_info">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.transcription_info"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.transcription_info">
    <xs:attribute name="first_transcription_date" use="required"/>
    <xs:attribute name="last_revision_date" use="required"/>
  </xs:attributeGroup>
  <!-- dd-mm-yyyy -->
  <!-- dd-mm-yyyy -->
  <xs:element name="editors">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.editors"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.editors">
    <xs:attribute name="name" use="required"/>
    <xs:attribute name="institution" use="required"/>
  </xs:attributeGroup>
  <!-- Vorname Nachname -->
  <xs:element name="content">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="body"/>
        <xs:element minOccurs="0" ref="translation"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="visual_element"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="body">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="div"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="div">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="text"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.div"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.div">
    <xs:attribute name="section" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="text"/>
          <xs:enumeration value="signature"/>
          <xs:enumeration value="marginalia"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:element name="text">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="people"/>
        <xs:element ref="place"/>
        <xs:element ref="lb"/>
      </xs:choice>
      <xs:attributeGroup ref="attlist.text"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.text">
    <xs:attribute name="method" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="printed"/>
          <xs:enumeration value="written"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="hand" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Antiqua"/>
          <xs:enumeration value="Kurrentschrift"/>
          <xs:enumeration value="Frakturschrift"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="language" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="German"/>
          <xs:enumeration value="French"/>
          <xs:enumeration value="Latin"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <!-- Explain why language tag here and not in source element: accompony letters which include several languages -->
  <xs:element name="people">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="lb"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.people"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.people">
    <xs:attribute name="name" use="required"/>
    <xs:attribute name="gender">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="male"/>
          <xs:enumeration value="female"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="confession">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Lutheran"/>
          <xs:enumeration value="Calvinist"/>
          <xs:enumeration value="Catholic"/>
          <xs:enumeration value="Anabaptist"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="role">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="recipient"/>
          <xs:enumeration value="issuer"/>
          <xs:enumeration value="witness"/>
          <xs:enumeration value="kin"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <!-- JG: this name functions as the ID -->
  <xs:element name="place">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="lb"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.place"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.place">
    <xs:attribute name="name" use="required"/>
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="place_of_birth"/>
          <xs:enumeration value="destination"/>
          <xs:enumeration value="place_of_issue"/>
          <xs:enumeration value="other"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="link"/>
  </xs:attributeGroup>
  <!-- JG: use the current, modern name for a place. This functions as the ID -->
  <!-- geburtsort|ausstellungsort|zielort|sonstige_Orte -->
  <!-- world historical gazetteer: http://whgazetteer.org/ or wikidata -->
  <xs:element name="lb">
    <xs:complexType/>
  </xs:element>
  <xs:element name="translation" type="xs:string"/>
  <xs:element name="visual_element">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.visual_element"/>
    </xs:complexType>
  </xs:element>
  <!-- JG: arguably needs further refinement -->
  <xs:attributeGroup name="attlist.visual_element">
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="coats_of_arms"/>
          <xs:enumeration value="cityscape"/>
          <xs:enumeration value="decorations"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="location">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="top_left"/>
          <xs:enumeration value="top_center"/>
          <xs:enumeration value="top_right"/>
          <xs:enumeration value="bottom_left"/>
          <xs:enumeration value="bottom_center"/>
          <xs:enumeration value="bottom_right"/>
          <xs:enumeration value="center"/>
          <xs:enumeration value="frame"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="specification"/>
  </xs:attributeGroup>
</xs:schema>
<!-- e.g. specify whether coats of arms is of a ruling house, guild, etc -->

=== ieg-dhr/DigitaleEditorikDMGK/G_16850731.xml
<?xml version="1.0" encoding="UTF-8"?>

<source xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://jg.dhlab.de/Teaching/Geburtsbriefe.xsd">
 
 <metadata>
  <archival_description ArchiveName="Stadtarchiv Mainz" ArchiveLocation="Mainz" Bestand="Urkundenbestand" Klassifikation="Geburtsbriefe" Signatur="G / 1685 Juli 31"/>
   <source_description source_ID="G16850731" catalogue_record="https://faust.mainz.de/objekt_start.fau?prj=internet&amp;dm=archiv&amp;zeig=123568" type="Geburtsbrief" place="Petit Rechain" date="31-07-1685" material_specifications=""/>
   <digital_surrogate filename="Geburtsbrief Jean le Pourceau" URL="https://teaching-dhlab.pages.gitlab.rlp.net/geburtsbriefemainz/pages/png/G16850731.JPG"/>
 </metadata>
 
 <edition>
   <transcription_info first_transcription_date="2021-04-21" last_revision_date="2021-07-16"/>
   <editors name="Yohan Park, Maren Reeb, Robert Zwick" institution="JGU Mainz"/>
 </edition>
 
 <content>
  <body>
   <div section="text">
    <text method="written" hand="Antiqua" language="French">
      Nous la Justi&#231;e d&#250; <place name="Petit-Rechain" type="place_of_issue" link="http://whgazetteer.org/places/13902634/portal">Petit Rechain</place> a&#250; D&#250;ch&#233; de <place name="Limbourg" type="other" link="http://whgazetteer.org/places/13662650/portal">Limbourg</place> Certifions<lb/>
   et attestons par la tene&#250;re des p[oi]ntes que no&#250;s a&#250;ons tres bonne connoissan&#231;e d&#39;a&#250;oir conn&#250;<lb/>
     et rep&#250;t&#233; fe&#250; <people name="Jean le Po&#250;rcea&#250;" gender="male" confession="Catholic" role="kin">Jean le Po&#250;rcea&#250;</people> jadis de son vi&#250;ant Procure&#250;r post&#250;lant parde&#250;ant n[ot]re<lb/>
     Justi&#231;e et <people name="Jeanne Dome des Champs" gender="female" confession="Catholic" role="kin">Jeanne Dome des Champs</people> sa Compagne conjoins par mariage&#44; Lesq&#250;els ont engendr&#233;<lb/>
     legitimement honn&#234;te <people name="Jeanne le Pourcea&#250;" gender="female" confession="Catholic" role="recipient">Jeanne</people> le&#250;r fille jce&#250;se jss&#250;s de tres bons parens&#44; a&#255;ants e&#250; l&#39;honne&#250;r<lb/>
     et la rep&#250;tation <people name="Jean le Po&#250;rcea&#250;" gender="male" confession="Catholic" role="kin">Jean le Pourcea&#250;</people> grand pere de lad[i]te fille <people name="Jeanne le Pourcea&#250;" gender="female" confession="Catholic" role="recipient">Jeanne&#44;</people> et a&#250;tres ses Predecesse&#250;rs<lb/>
   de descendre de la Ra&#231;e des Po&#250;rcea&#250;x dans le&#250;r armerie consiste des la Date des l&#39;an traize<lb/>
   cent nonante six, lesq&#250;els no&#250;s a&#250;ons pe&#250;[t] &#234;tre reput&#233;z comme no&#250;s rep&#250;tons jceux Predecesse&#250;rs<lb/> 
   &#234;tre Gentilhommes&#44; Chevaliers&#44; Ese&#250;&#255;ers&#44; to&#250;s gens selon Die&#250; de bien et d&#39;honne&#250;r, des bonne fame<lb/>
   et rep&#250;tation&#44; et d&#39;un parent&#233; a&#250;rant bien mo&#255;enn&#233; q&#250;&#39;auc&#250;n le puisse trou&#250;er dans n[ot]re Jurisdiction<lb/> 
   sans qu&#39;il soit ven&#250; a [le]ure connoissan&#231;e&#44; q&#250;&#39;il no&#250;s soit appar&#250; a&#250;c&#250;n act de reprehension q&#250;elconq[ue]<lb/> 
   qui po&#250;rroit ternir n&#255; denigrer [aulc&#250;ne] sorte de personnes de bien et d&#39;honneur&#59; C&#39;est pourquo&#255;<lb/>
   en faue&#250;r de Justi&#231;e et de la verit&#233; no&#250;s a&#250;ons bien voul&#250; depecher les p[oi]ntes lettres d&#39;attes&#61;<lb/>
   &#61;tations&#44; et supplier tres h&#250;mblement to&#250;s ce&#250;s&#44; o&#250; jcelles par&#250;iendront de le&#250;r donner Fo&#255; et Credence<lb/> 
     afin q&#250;e laditte <people name="Jeanne le Pourcea&#250;" gender="female" confession="Catholic" role="recipient">Jeanne</people> soit toujo&#250;rs ten&#252;e et rep&#250;t&#233;e iss&#252;e de tres bon et tres honn&#234;te parentage&#44;<lb/> 
   fille de bien et d&#39;honne&#250;r professant en Jes&#250;s Christ la vra&#255; Fo&#255; orthodoxe&#44; Comme auss&#255; po&#250;r<lb/> 
   ce regard lu&#255; donner toutte aide&#44; faue&#250;r et asssistan&#231;e raisonnable le Cas le req&#250;erant&#44; ains&#255;<lb/>
   q&#250;e no&#250;s voudrions faire en Etant requis in forma&#44; En Fo&#255; de quo&#255; et temoignage de la<lb/> 
   verit&#233; no&#250;s a&#250;ons aux p[oi]ntes fait impresser n[ot]re Seel Scabinal en tels er semblables Cas<lb/>
   acco&#250;tum&#233;&#44; et ordonn&#233; a n[ot]re Greffier Serment&#233; de les soubsigner s&#250;r l&#39;an de gra&#231;e de<lb/> 
   n[ot]re Seigne&#250;r mil six cent q&#250;attre vint et cinq d&#250; mois de Juillet Le trente unieme.<lb/>
   </text></div>
   <div section="signature">
     <text method="written" hand="Antiqua" language="French">
       Par ordonnance du [judiciaire?]<lb/>
       sudit<lb/>
       <people name="unclear">[...]</people> Greffier
     </text>
   </div>
  </body>
  <translation>
    Wir, die Gerichtsbarkeit von Petit-Rechain im Herzogtum Limburg bescheinigen 
    und bezeugen durch den genauen Inhalt dieser Punkte, dass wir sehr gutes Wissen von der Bekanntschaft 
    und Reputation des verstorbenen Jean le Pourceau haben von seinem noch lebenden Anwalt [Procureur], der vor unserer 
    Gerichtsbarkeit bekr&#xE4;ftigt, und von Jeanne Dome des Champs, seiner Gattin, verbunden durch die Ehe, 
    die rechtm&#xE4;ßig gezeugt haben die geehrte Jeanne, ihre besagte Tochter, die hervorgegangen ist von sehr guten Eltern, die die Ehre 
    und den Ruf hatten von Jean le Pourceau, dem Großvater ihrer Tochter Jeanne, und von anderen seiner Vorfahren 
    aus dem Geschlecht der Pourceaux abzustammen [und ihnen] in ihre Waffenkammer, die besteht seit dem Datum des Jahres 1396, 
   [nachzufolgen] [und] die uns vielleicht in der gleichen Weise beleumdet haben wie wir jetzt deren Vorfahren beleumden, 
   Edelleute, Ritter, [und] Escuijers [Esquire, Ehrentitel eines wappentragenden Mannes unterhalb des Ritterrangs], gewesen zu sein, alles Menschen vor Gott mit G&#xFC;tern 
   und Ehre, von gutem Ruf und Leumund, und von einer Verwandtschaft, die so beg&#xFC;tert / angesehen geworden ist, wie niemand sie sonst ihn in unserer Gerichtsbarkeit 
   finden kann, ohne dass es allgemein bekannt geworden w&#xE4;re[.] [Wir best&#xE4;tigen außerdem,] dass kein Akt irgendeines Tadels vorgefallen ist, der irgendeine Art von 
   beg&#xFC;terten und ehrenhaften Personen betr&#xFC;ben oder herabw&#xFC;rdigen könnte;
    Deshalb haben wir uns gerne bereit erkl&#xE4;rt, den Brief der Beglaubigung im Dienste von Gerechtigkeit und Wahrheit zu verschicken, und bitten sehr untert&#xE4;nig all jene, 
    wo die genannte Person [Jeanne] hinkommen wird, ihr Glauben und Vertrauen zu geben, so dass Jeanne immer f&#xFC;r guter und sehr ehrenhafter Abstammung gehalten und 
    beleumdet werden m&#xF6;ge, als wohlhabendes und ehrenhaftes M&#xE4;dchen [junge unverheiratete Frau], das in Jesus Christus den wahren rechten Glauben [Katholizismus] 
    praktiziert, und ihr auch im Hinblick darauf alle Hilfe, Wohltat und angebrachte Unterst&#xFC;tzung zu geben, die der Schritt [ihr Weg] erfordert, so wie wir das auch 
    tun m&#xF6;chten, indem wir formell, zu Urkund und Zeugnis der Wahrheit unser gedrucktes Siegel angeh&#xE4;ngt haben, 
    und unseren Justizbeamten gebeten haben, es zu unterzeichnen im Jahr der Gnade unseres HERRN 1685 im Monat Juli am 30.
  </translation>
  <visual_element type="coats_of_arms" location="bottom_left" specification="vermutlich Wappen des Gerichts in Petit-Rechain"></visual_element>
  
 </content>
</source>

=== ieg-dhr/DigitaleEditorikDMGK/G_16850801.xml
<?xml version="1.0" encoding="UTF-8"?>

<source xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://jg.dhlab.de/Teaching/Geburtsbriefe.xsd">
	<metadata>
		<archival_description ArchiveName="Stadtarchiv Mainz" ArchiveLocation="Mainz"
			Bestand="Urkundenbestand" Klassifikation="Geburtsbriefe" Signatur="G / 1685 August 1"/>
		<source_description source_ID="G_16850801"
			catalogue_record="https://faust.mainz.de/objekt_start.fau?prj=internet&amp;dm=archiv&amp;zeig=123569"
			type="Geburtsbrief" place="Andrimont" date="1685-08-01"
			material_specifications="Pergament" seal="wax"/>
		<!--JG: working link for quick navigation: https://faust.mainz.de/rech.FAU?sid=C043A6263&dm=1&auft=1-->
		<digital_surrogate filename="archivaliendatenbank_7.png"
			URL="https://teaching-dhlab.pages.gitlab.rlp.net/geburtsbriefemainz/pages/png/G16850801.JPG"/>
		<!-- https://faust.mainz.de/zvimg.FAU?sid=C043A626&DM=1&qpos=123569&ipos=1&erg=A&hst=1&rpos=archivaliendatenbank.png-->
	</metadata>
	<edition>
		<transcription_info first_transcription_date="10-05-2021" last_revision_date="21-05-2021"/>
		<editors name="Maximilian Michel" institution="Johannes Gutenberg-Universität Mainz"/>
	</edition>
	<content>
		<body>
			<div section="text">
				<text method="written" hand="Antiqua" language="Latin"> Omnibus has visuris
					salus<lb/> ab eo qui vera est salus<lb/> Cum Honesta ac virtute Clara Domicella
						<people name="Jeanne le Pourceaux" gender="female" role="recipient"
						>Joanna</people> Filia Clarissimi<lb/> et Honestissimi <people
						name="Jean le Pourceaux" gender="male" role="kin">Joannis le
						Pourceaux</people>, cuius originem videre licet ex attestatione<lb/> a
					Dominis <people name="Scabin de Richain" gender="male">Scabinis de
						Richain</people> dat&#226;, et virtuosissim&#230; <people
						name="Jeanne Dominici de Champs" gender="female" role="kin">Joann&#230; Dominici de
						Champs</people><lb/> in Patri&#226; <place name="Lüttich" type="other"
						link="http://whgazetteer.org/places/12904628/portal">Leodiensi</place>, <!--JG: historic_name attribute and its value can be deleted-->
					<place name="Franchimont" type="other"
						link="http://whgazetteer.org/places/12353020/portal">Marchionatu
						Franchimontano</place>, et in pago <place name="Andrimont"
						type="place_of_issue" link="http://whgazetteer.org/places/12502346/portal"
						>Andrimontensi</place><lb/> oriunda baptismi Sui me testem esse voluerit,
					non potui eius tam honesta[e]<lb/> petitioni non annuere, &#234;quidem non
					potens ex registro baptismali, cum illud<lb/> a militibus anno 1674 Sublatum
					Fuerit, ex ipsius e Sacro baptismatis fonte Susceptoris <lb/> didici,
					apert&#233; coram me declarantibus sese, nempe <people name="Jean Bertrand"
						gender="male" role="witness">Joannem Bertrandi</people> et <people
						name="Pentecoston le Boos" gender="male" role="witness">Pentecoston<lb/> le
						Boos</people>, ab anno decimo octauo in nostr&#226; Ecclesi&#226; <people
						name="Jeanne le Pourceaux" gender="female" role="recipient">Joanna</people>
					in Filiam <people name="Jean le Pourceaux" gender="male" role="kin">Joannis le
						Pourceaux</people><lb/> et <people name="Jeanne Dominici de Champs"
						gender="female" role="kin">Joanna Dominici de Champs</people> legitime junctorum
					suscepisse, et cum ita sit quod in hoc nostro<lb/> Pago ab omni h&#230;resi
					longissim&#233; remoto nullus de h&#226;c re detur dubitandi locus<lb/>
					accedentibus desuper declarationibus, rogo omnes ad quos peruenerit,<lb/> hanc
					pro tali existimare, in quorum fidem hasce p[ro]pri&#226; manu scripsi,
					subscripsi<lb/> et p[ro]prio sigillo muniui, Datum in &#230;dibus nostris in
					Pago <place name="Andrimont" type="place_of_issue"
						link="http://whgazetteer.org/places/12502346/portal"
					>Andrimontesi</place>,<lb/> h&#226;c prim&#226; Augusti Anno a natiuitate
					D[omi]ni 1685 - <lb/>
				</text>
			</div>
			<div section="signature">
				<text method="written" hand="Antiqua" language="Latin"> Ita est <people
						name="Tossanus Petit" role="issuer" gender="male">Tossanus
					Petit</people><lb/> Dit De Scolombs vice Pastor<lb/>
					<place name="Andrimont" type="place_of_issue"
						link="http://whgazetteer.org/places/12502346/portal">Andrimontis</place>
				</text>
			</div>
		</body>
		<translation>
			Allen, die diese [Zeilen] sehen, [sei] Heil von dem, der das wahre Heil ist.
			
			Mit offensichtlicher Ehrbarkeit und Tugend hat die Edelfrau Joanna, die Tochter der ber&#252;hmtesten und 
			ehrenwertesten und Jean le Pourceaux, deren Herkunft aus der Best&#228;tigung hervorgeht, 
			die von Herrn Scabin de Richain ausgestellt wurde, und der tugendhaftesten Jeanne Dominici de Champs, 
			beheimatet in L&#252;ttich, in der Grafschaft Franchimont, und im Dorf Andrimont [heute Teil der Gemeinde Dison in Belgien] geboren, 
			gew&#252;nscht, dass ich Zeuge ihrer Taufe sei, [aber] ich bin nicht in der Lage, die Bitte dieser so ehrenhaften [Frau] zur&#252;ckzuweisen, 
			obwohl es mir gleichfalls nicht m&#246;glich ist, den Beweis aus dem Taufregister zu erbringen, weil jenes 
			im Jahr 1674 von Soldaten weggenommen wurde, [doch] von den Paten derselben, die sich mir gegen&#252;ber offen erklärt haben, 
			n&#228;mlich Jean Bertrand und Pentecoston le Boos, habe ich von ihrer heiligen Taufe erfahren, nachdem sie 
			von dem seit dem achtzehnten Jahr in unserer Kirche rechtm&#228;ßig verheirateten Paar Jean le Pourceaux und Jeanne Dominici de Champs 
			als Tochter empfangen wurde, und weil so in der Tat in unserem Dorf, das weit von jedem Irrglauben entfernt ist, kein Zweifel in dieser Sache 
			über den Ort [der Taufe] bestehen kann, im Sinne der oben genannten Erkl&#228;rung, bitte ich alle, zu denen sie kommen wird, 
			diese für eine solche Frau anzuerkennen. Zur Beurkundung wurde dieses in eigener Hand geschrieben, unterschrieben und mit dem ordentlichen 
			amtlichen Siegel versehen, gegeben in unserem Amtssitz im Dorf Andrimont, an diesem 1. August im Jahr der Geburt des Herrn 1685.
			
			So ist es nach Tossanus Petit, gegeben vom [Scolombs?] Dorfpastor Andrimont
		</translation>
		<visual_element type="coats_of_arms" location="top_left" specification="coat of arms"/>
	</content>
</source>

=== ieg-dhr/DigitaleEditorikDMGK/G_17980302r.xml
<?xml version="1.0" encoding="UTF-8"?>

<source xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://jg.dhlab.de/Teaching/Geburtsbriefe.xsd">

 <metadata>
  <archival_description ArchiveName="Stadtarchiv Mainz" ArchiveLocation="Mainz"
   Bestand="Urkundenbestand" Klassifikation="Geburtsbriefe" Signatur="G / 1798 März 2"/>
  <source_description source_ID="G17980302r"
   catalogue_record="https://faust.mainz.de/hzeig.FAU?sid=A8CF0B4F21&amp;dm=1&amp;ind=1&amp;zeig=G+/+1798+M%E4rz+2"
   type="Lehrbrief" place="Wien" date="1798-03-02"/>
  <digital_surrogate filename="Geburtsbrief Georg Gramer"
   URL="https://faust.mainz.de/zvimg.FAU?sid=A8CF0B4F&amp;DM=1&amp;qpos=129736&amp;ipos=1&amp;erg=H&amp;hst=1&amp;rpos=archivaliendatenbank.png"
  />
 </metadata>

 <edition>
  <transcription_info first_transcription_date="2021-04-21" last_revision_date="2021-06-18"/>
  <editors name="Yohan Park, Maren Reeb, Robert Zwick" institution="JGU Mainz"/>
 </edition>

 <content>
  <body>
   <div section="text">
    <text method="printed" hand="Frakturschrift" language="German"> Wir Vorsteher und gesamte
     Meister des ehrsamen Handwerks der b&#252;rgerl&#58;[ichen] Tischlern in der K&#58;[aiserlich]
     K&#58;[öniglichen] Haubt &#61;<lb/> und Residenz Stadt <place name="Wien" type="place_of_issue"
      link="http://whgazetteer.org/places/12346175/portal">Wien</place> (beglaubigen) hiermit&#44;
     da&#223; gegenwertiger Tischlergesell&#44; Namens <text method="written" hand="Kurrentschrift"
      language="German"><people name="Georg Gramer" role="recipient">Georg
     Gramer</people></text><lb/> von <text method="written" hand="Kurrentschrift" language="German"
       ><place name="Mainz" type="place_of_birth"
       link="http://whgazetteer.org/places/13067462/portal">Maintz</place></text> &#45; &#45;
     geb&#252;rtig&#44; welcher <text method="written" hand="Kurrentschrift" language="German"
      >29</text> Jahre alt und von <text method="written" hand="Kurrentschrift" language="German"
      >mittlerer</text> Statur&#44; auch <text method="written" hand="Kurrentschrift"
      language="German">schwarz</text> an<lb/> Haaren ist, bey <b>uns</b> alhier 6 1&#47;2
     Jahre&#44; &#45; Wochen in Arbeit gestanden&#44; und sich w&#228;hrend dieser<lb/> Zeit
     treu&#44; flei&#223;ig&#44; still&#44; friedsam&#44; und ehrlich&#44; wie es einem jeden
     rechtschaffenen Handwerks Gesel&#61;<lb/> len geb&#252;hret&#44; verhalten habe&#58; welches
     nicht nur allein von uns&#44; sondern auch von unserern<lb/> l&#246;blichen <b>Stadt
      Magistrat</b> hiermit attestiert wird&#46; Daher ergehet an unsere s&#228;mmentliche
     Mitmeis&#61;<lb/> ter <b>unser</b> dienstfreundliches Ersuchen&#44; womit dieser Gesell nach
     Handwerks Gebrauch &#252;ber&#61;<lb/> all gef&#246;rdert werden m&#246;chte&#246; Gegeben
      <place name="Wien" type="place_of_issue" link="http://whgazetteer.org/places/12346175/portal"
      >Wien</place> den<text method="written" hand="Kurrentschrift" language="German">2</text>ten
      <text method="written" hand="Kurrentschrift" language="German">M&#228;rtz</text> Anno <text
      method="written" hand="Kurrentschrift" language="German">798</text><lb/>
    </text>
   </div>
   <div section="signature">
    <text method="printed" hand="Kurrentschrift" language="German">
     <people name="Anton Sigel">A:[nton] Sigel</people> gn:[] et Del:[ineavit]<lb/>
     <people name="Franz Landerer">F&#61; Landerer</people> Sculp&#61;[sit] </text>
   </div>
   <!-- <image type="column" position="left"> -->
   <div section="text">
    <text method="printed" hand="Kurrentschrift" language="German"> Erster<lb/> Vorsteher<lb/>
    </text>
   </div>
   <div section="signature">
    <text method="written" hand="Kurrentschrift" language="German">
     <people name="unclear" role="witness">Johann<lb/> [Wohlbret]</people>
    </text>
   </div>
   <!-- <image type="column" position="right"> -->
   <div section="text">
    <text method="printed" hand="Kurrentschrift" language="German"> Zwa&#255;ter<lb/> Vorsteher<lb/>
    </text>
   </div>
   <div section="signature">
    <text method="written" hand="Kurrentschrift" language="German">
     <people name="unclear" role="witness">Johann Gottlieb<lb/> [Wiesenguth]</people>
    </text>
   </div>
  </body>
  <visual_element type="cityscape" location="top_center" specification="Stadtansicht von Wien"/>
  <visual_element type="coats_of_arms" location="center" specification="aufgeklebtes Wappen"/>
 </content>
</source>
