=== ieg-dhr/DigitaleEditorikDMGK/DMGK 9p XML schema/Geburtsbriefe.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="source">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="metadata"/>
        <xs:element ref="edition"/>
        <xs:element ref="content"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="metadata">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="archival_description"/>
        <xs:element ref="source_description"/>
        <xs:element ref="digital_surrogate"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- For archival descriptions in XML, see e.g. https://www.loc.gov/ead/ead3schema.html -->
  <xs:element name="archival_description">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.archival_description"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.archival_description">
    <xs:attribute name="ArchiveName" use="required"/>
    <xs:attribute name="ArchiveLocation" use="required"/>
    <xs:attribute name="Bestand" use="required"/>
    <xs:attribute name="Klassifikation" use="required"/>
    <xs:attribute name="Signatur" use="required"/>
  </xs:attributeGroup>
  <xs:element name="source_description">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.source_description"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.source_description">
    <xs:attribute name="source_ID" use="required"/>
    <xs:attribute name="related_object"/>
    <xs:attribute name="catalogue_record" use="required"/>
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Geburtsbrief"/>
          <xs:enumeration value="Lehrbrief"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="place" use="required"/>
    <xs:attribute name="date" use="required"/>
    <xs:attribute name="material_specifications"/>
    <xs:attribute name="seal">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="wax"/>
          <xs:enumeration value="printed"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <!-- Gyyyymmdd or Lyyyymmdd, no dots between numbers -->
  <!-- -reference to source ID of related transcription, in case of a letter with data on the verso side -->
  <!-- URL of individual record in the online catalogue -->
  <!-- Ausstellungsort -->
  <!-- dd-mm-yyyy -->
  <!-- Materialangaben -->
  <!-- angeheftet/ausgedruckt -->
  <!--  JG: still not sure, should it be part of visual elements or new element entirely? And should we mention it's material, e.g. paper or wax? Is implied now -->
  <xs:element name="digital_surrogate">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.digital_surrogate"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.digital_surrogate">
    <xs:attribute name="filename"/>
    <xs:attribute name="URL"/>
  </xs:attributeGroup>
  <xs:element name="edition">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="transcription_info"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="editors"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="transcription_info">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.transcription_info"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.transcription_info">
    <xs:attribute name="first_transcription_date" use="required"/>
    <xs:attribute name="last_revision_date" use="required"/>
  </xs:attributeGroup>
  <!-- dd-mm-yyyy -->
  <!-- dd-mm-yyyy -->
  <xs:element name="editors">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.editors"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.editors">
    <xs:attribute name="name" use="required"/>
    <xs:attribute name="institution" use="required"/>
  </xs:attributeGroup>
  <!-- Vorname Nachname -->
  <xs:element name="content">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="body"/>
        <xs:element minOccurs="0" ref="translation"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="visual_element"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="body">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="div"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="div">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="text"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.div"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.div">
    <xs:attribute name="section" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="text"/>
          <xs:enumeration value="signature"/>
          <xs:enumeration value="marginalia"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:element name="text">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="people"/>
        <xs:element ref="place"/>
        <xs:element ref="lb"/>
      </xs:choice>
      <xs:attributeGroup ref="attlist.text"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.text">
    <xs:attribute name="method" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="printed"/>
          <xs:enumeration value="written"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="hand" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Antiqua"/>
          <xs:enumeration value="Kurrentschrift"/>
          <xs:enumeration value="Frakturschrift"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="language" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="German"/>
          <xs:enumeration value="French"/>
          <xs:enumeration value="Latin"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <!-- Explain why language tag here and not in source element: accompony letters which include several languages -->
  <xs:element name="people">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="lb"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.people"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.people">
    <xs:attribute name="name" use="required"/>
    <xs:attribute name="gender">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="male"/>
          <xs:enumeration value="female"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="confession">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Lutheran"/>
          <xs:enumeration value="Calvinist"/>
          <xs:enumeration value="Catholic"/>
          <xs:enumeration value="Anabaptist"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="role">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="recipient"/>
          <xs:enumeration value="issuer"/>
          <xs:enumeration value="witness"/>
          <xs:enumeration value="kin"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <!-- JG: this name functions as the ID -->
  <xs:element name="place">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="lb"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.place"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.place">
    <xs:attribute name="name" use="required"/>
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="place_of_birth"/>
          <xs:enumeration value="destination"/>
          <xs:enumeration value="place_of_issue"/>
          <xs:enumeration value="other"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="link"/>
  </xs:attributeGroup>
  <!-- JG: use the current, modern name for a place. This functions as the ID -->
  <!-- geburtsort|ausstellungsort|zielort|sonstige_Orte -->
  <!-- world historical gazetteer: http://whgazetteer.org/ or wikidata -->
  <xs:element name="lb">
    <xs:complexType/>
  </xs:element>
  <xs:element name="translation" type="xs:string"/>
  <xs:element name="visual_element">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.visual_element"/>
    </xs:complexType>
  </xs:element>
  <!-- JG: arguably needs further refinement -->
  <xs:attributeGroup name="attlist.visual_element">
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="coats_of_arms"/>
          <xs:enumeration value="cityscape"/>
          <xs:enumeration value="decorations"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="location">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="top_left"/>
          <xs:enumeration value="top_center"/>
          <xs:enumeration value="top_right"/>
          <xs:enumeration value="bottom_left"/>
          <xs:enumeration value="bottom_center"/>
          <xs:enumeration value="bottom_right"/>
          <xs:enumeration value="center"/>
          <xs:enumeration value="frame"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="specification"/>
  </xs:attributeGroup>
</xs:schema>
<!-- e.g. specify whether coats of arms is of a ruling house, guild, etc -->

=== ieg-dhr/DigitaleEditorikDMGK/G_17690822.xml
<?xml version="1.0" encoding="UTF-8"?>

<source xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://jg.dhlab.de/Teaching/Geburtsbriefe.xsd">
 <metadata>
       <archival_description ArchiveName="Stadtarchiv Mainz" ArchiveLocation="Mainz" 
        Bestand="Urkundenbestand" Klassifikation="Lehrbrief" Signatur="G / 1769 August 22"/>
       <source_description source_ID="G17690822" 
        catalogue_record="https://faust.mainz.de/rech.FAU?sid=EFC668DB7&amp;dm=1&amp;auft=1" 
        type="Lehrbrief" place="Mainz" date="1769-08-22" 
        material_specifications="Papier" seal="printed"/>           
       <digital_surrogate filename="archivaliendatenbank.png" 
        URL="https://faust.mainz.de/rech.FAU?sid=EFC668DB7&amp;dm=1&amp;auft=1"/>
   </metadata>
 
   <edition>
           <transcription_info first_transcription_date="2021-05-22" last_revision_date="2021-07-16"/> 
   <editors name="Viviane El-Garrahi, Konstantin Arnold" institution="Johannes Gutenberg-Universität Mainz"/> 
   </edition>
 
   <content>
   <body>
 <div section="text">  
  <text method="printed" hand="Frakturschrift" language="German">Wir Beschworne Vor und An-<lb/>
  dere Meister des Ehrsamen Handwercks<lb/>
  der <text method="written" hand="Kurrentschrift" language="German">Ma&#361;rer</text> Zunfft, in der <place name="Mainz" type="place_of_issue" link="http://whgazetteer.org/places/13067462/portal">Stadt Ma&#255;ntz</place> bekennen hiermit das<lb/>
  gegenw&#228;rtiger Gesell Nahmens <text method="written" hand="Kurrentschrift" language="German"><people name="Karl Anton Mayer" gender="male" confession="Catholic" role="recipient">Carl Anton Mayer</people></text> von <text method="written" hand="Kurrentschrift" language="German"><place name="Mainz" type="place_of_birth">Ma&#255;ntz</place></text> geb&#252;rtig<lb/>
  so <text method="written" hand="Frakturschrift" language="German">19</text> Jahr alt &#361;nd von Stat&#361;r <text method="written" hand="Kurrentschrift" language="German">gut</text> a&#361;ch <text method="written" hand="Kurrentschrift" language="German">bl&#361;nt</text> von Haaren ist bey &#361;ns allhier<lb/>
  1 Jahr &#8212; Wochen in Arbeit gestanden &#361;nd solche Zeit &#252;ber Tre&#361; Flei&#223;ig Still Fridsam &#361;nd Ehr-<lb/>
  lich, wie einem jeglichen Handwercks Gesellen geb&#252;hret verhalten hat, welches wir also Attestiren<lb/>
  &#361;nd de&#223;halben &#361;nsere sambtliche Mit Meister diesen Gesellen nach Handwercks Gebra&#361;ch &#252;berall<lb/>
   Z&#361;f&#246;rdern geziement ers&#361;chen wollen <place name="Mainz" type="place_of_issue" link="http://whgazetteer.org/places/13067462/portal">Ma&#255;ntz</place> den <text method="written" hand="Kurrentschrift" language="German"> >22[sten] A&#361;g&#361;st</text> Anno <text method="written" hand="Frakturschrift" language="German">1769</text><lb/>
  <text method="written" hand="Kurrentschrift" language="German">
  Erh&#228;lt aus neuen Allmosen zu <place name="Straßburg" type="destination" link="http://whgazetteer.org/places/12481324/portal">Stra&#223;<lb/>
  burg</place> 2 &#223; [Schillinge?] d. 30ter [Octo]bris. 1769. Ritter<lb/></text>
  </text></div>  
    
  <div section="signature">
    <text method="written" hand="Kurrentschrift" language="German">
   &#196;ltester Geschworne Meister<lb/> 
   <people name="Jacob Anspach" gender="male" role="witness">Jacob Anspach</people><lb/>
   Jungster Geschworne Meister<lb/>
   <people name="Joseph Dörr" gender="male" role="witness">Joseph D&#246;r</people><lb/>
    Meister wo Obiger Gesell<lb/>
    in Arbeit gestanden<lb/> 
   <people name="Simon Neurohr" gender="male" role="witness">Simon Neurohr</people><lb/>
   Ma&#361;rer Meister<lb/>
  </text>
 </div>
 
<div section="marginalia"> 
 <text method="written" hand="Kurrentschrift" language="German">
 Pass:[um]<place name="Burgdorf" type="destination" link="http://whgazetteer.org/places/13360070/portal">B&#361;rgdorf</place> d[en] 21ten 9bris [Novembris] 1769<lb/>
 <people name="unclear" gender="male" role="witness">Wi[lhelm] R[itter]</people><lb/>
 <place name="Straßburg" type="other" link="http://whgazetteer.org/places/12481324/portal">Strasburg</place> d[en] 29ten [Octo]bris 1769.<lb/>
 <people name="George Christophe Freysinger" gender="male" role="witness">G[eorge] C[hristophe] Fre&#255;singer</people> Ober Meister.<lb/>
 <place name="Lindau" type="destination" link="http://whgazetteer.org/places/12653456/portal">Linda&#361;</place> d. 5t. [Decem]br[is] 1769.<lb/>
 Pa&#223;irt<lb/>
 <place name="Straßburg" type="destination" link="http://whgazetteer.org/places/12481324/portal">Stra&#223;b&#361;rg</place><lb/>
  d 27 [Octo]bris<lb/>
  1769 um 4 uhr<lb/>
  a
 </text>
</div>
</body> 
    
<visual_element type="cityscape" location="center" specification="Stadtansicht von Wien mit Stephansdom"/>
<visual_element type="coats_of_arms" location="top_center" specification="Kaiserliches Wappen und zwei weitere Wappen, ggf. für die Stadt Wien und die Zunft"/>
<visual_element type="decorations" location="frame" specification="Barockes Portal mit zwei antikisierenden Säulen"/>
</content>
</source>

=== ieg-dhr/DigitaleEditorikDMGK/G_16960102.xml
<?xml version="1.0" encoding="UTF-8"?>

<source xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://jg.dhlab.de/Teaching/Geburtsbriefe.xsd">

	<metadata>
		<archival_description ArchiveName="Stadtarchiv Mainz" ArchiveLocation="Mainz" Bestand="Urkundenbestand" Klassifikation="Geburtsbriefe" Signatur="G / 1696 Januar 2"/>
		<source_description source_ID="G16960102" catalogue_record="https://faust.mainz.de/objekt_start.fau?prj=internet&amp;dm=archiv&amp;zeig=123708" type="Geburtsbrief" place="Loco Valle Onsernone" date="1696-01-02" material_specifications="Pergament"/>
		<!-- Siegel fehlt -->
		<digital_surrogate filename="Geburtsbrief Remigius Meletta" URL="/geburtsbriefemainz/pages/png/G16960102.JPG"/>
	</metadata>

	<edition>
		<transcription_info first_transcription_date="2021-05-21" last_revision_date="2021-07-20"/>
		<editors name="Linnaea Söhn" institution="JGU Mainz"/>
	</edition>

	<content>
		<body>
			<div section="text">
				<text method="written" hand="Antiqua" language="Latin"> NOS <people name="Johannes Baptist Nizoli" gender="male">IOANNES BAPTISTA NIZOLA</people> p[ro] t[empore] CONSVL<lb/>
					Communis, et homines <place name="Loco" type="place_of_issue" link="http://whgazetteer.org/places/13458395/portal">Loci Vallis Lusarnonnensis</place>, Di&#339;cesis <place name="Como" type="other" link="http://whgazetteer.org/places/12862979/portal">Comensis</place> Subditi M:[axi]mor&#361;[m] et Potentiss:[simo]rum<lb/>
					Dominorum duodecim Cantonum inviolabilis <place name="Schweiz" type="other" link="http://whgazetteer.org/places/14152995/portal">conf&#339;derationis Helveti&#230;</place> fidem facimus et attestamur:<lb/>
					D[ominu]m <people name="Remigius Meletta" gender="male" role="recipient">Remigium Melettam</people> filiu[m] <people name="Petrus Meletta" gender="male" role="kin" >Petri Mellett&#230;</people> et <people name="Johanna de la Chiesa" gender="female" role="kin">Gioann&#230; de la chiesa</people> vxoris ejusdem pr&#230;dicti <people name="Petrus Meletta" gender="male" role="kin">Petri</people><lb/>
					Nostrum dilectum vicinum natum A[nn]o 1658. 31a [Octo]bris], baptizatum ver&#242; 2da [secunda] [Novem]bris pr&#230;dicti Anni astantib[us]<lb/>
					Petri Patrino Mag[ist]ro D[omi]no <people name="Jacob Cantarino" gender="male" role="witness">Jacobo Cantarino</people> <!-- Pate -->, et Patrin&#227; D[omin]a <people name="Helena" gender="female" role="witness">Helena</people><!-- Patin, Nachname nicht explizit genannt --> Vxore D[omi]ni <people name="Petrus Regolato" gender="male">Petri Regolati</people><!-- Mann der Patin Helena--> Syndici ejusdem <place name="Valle Onsernone" type="place_of_birth" link="http://whgazetteer.org/places/12586942/portal">Vallis<lb/>
					Lusarnonnensis</place> de legitimo matrimonio susceptum antiqvissim&#226; et honestissima prole familiaq[ue] deductum esse,<lb/>
					qvinimo toto vit&#230; ejus decursu actionibus suis honestis, moribusq[ue] compositum semper extitisse, ut nullus<lb/>
					adsit, qui de supradicti vita et moribus conqveri possit; C&#363;m tamen ejus honestati vitaq[ue] integritati sit<lb/>
					devictus nec minus ob aliquod ejus crimen a nobis recedere cogitur, sed ad lucrum et victum honestis sudo-<lb/> 
					ribus ejus arte melius conqvirendum. Qvapropter Benevolos lectores, ad qvos h&#230; nostr&#230; patentes devenerint<lb/>
					enix&#232; rogamus, hunc nostrum nobis adm[odum] dilectum beneq[ue] meritum vicinum supra Nominatum <people name="Remigius Meletta" gender="male" role="recipient">Remigium Melleta[m]</people><lb/>
					omni humanitate, benevolentia, et charitate suscipere ac promovere, susceptumq[ue] sibi commendatum habere<lb/>
					velint&#59; idipsum in omni simili eventu pr&#230;stituros erga ipsius benevolos, atq[ue] c&#230;teros omnes honestati deditos,<lb/>
					promittentes. Ad qvorum majorem fidem publico Communitatis nostr&#230; Cancellario mandavimus has patentes<lb/>
					vices nostras exarare, ejusq[ue] consveto Sigillo muniri dignaretur&#59; inq[ue] plenariam omnium horum corroborationem<lb/>
					rogavimus suppliciter Ill[ustrissimum] adm[odum] atq[ue] magnificum D. <people name="Johannes Faber" gender="male" role="issuer">Joannem Fabri</people> nostrum de pr&#230;senti Col[endissi]mumsatrapam<lb/>
					ac Pr&#230;torem, ut semetipsum subferiberet&#59; qvod idem confirmare adm[odum] R[everen]dus atq[ue] perdoctus D[omi]nus Eccl[es]i&#230;<lb/>
					nostr&#230; Pr&#230;positus Parochus non dedignatus est. Dat&#230; <place name="Loco" type="place_of_issue" link="http://whgazetteer.org/places/13458395/portal">Loci Vallis Lusarnonnensis</place> die 2a Jannuarij Anno<lb/>
					Salutis nostr&#230; M.DC.LXXXXVI.
				</text>
			</div>
			<div section="signature">
				<text method="written" hand="Antiqua" language="Latin">
					<people name="Johannes Faber" gender="male" role="issuer">Johann Fabri</people><!-- unclear --> Landt [Wa]cht <!--  -->
				</text>
			</div>
			<div section="signature">
				<text method="written" hand="Antiqua" language="Latin">
					<people name="Johannes Baptist Nizoli" gender="male" role="issuer">Joannes Baptista</people> Quadri<lb/>
					p[ro] t[empore] Parochus <place name="Loco" type="place_of_issue" link="http://whgazetteer.org/places/13458395/portal">Loci Vallis<lb/>
					Lusarnonnensis</place> et notarius<lb/>
					Ap[ostoli]cus<lb/>
					Mproia 
				</text>
			</div>
		</body>
		<"translation">Wir Johannes Baptist Nizoli, KONSUL der Gemeinde auf Zeit,
            und die Menschen / Männer aus Loco im Onsernonetal [wörtlich: Valle Lusarnonnensis], die dem Rat der ältesten / mächtigsten Herren des Bistums Como Untertan sind in den zwölf Kantonen der unverletzlichen Schweizer Eidgenossenschaft, schenken Glauben und bekennen:
            dass der Herr Remigius Meletta, der Sohn des Petrus Meletta und der Johanna de la Chiesa, der Frau des genannten Petrus, im Jahr 1658 am 31. Oktober als unser geliebter Nachbar geboren wurde, jedoch am 2. November des genannten Jahres getauft wurde, wobei Herr Magister Jacob Cantarino als Pate und Frau Helena, die Frau des Anwalts Petrus Regolato aus demselben Onsernonetal [wörtlich: Valle Lusarnonnensis] als Patin anwesend waren, [und dass der Täufling] in gültiger Ehe empfangen wurde und aus einer alteingesessen und allerehrwürdigsten Familie als Nachwuchs hervorging[.]
            Tatsächlich war der gesamte Verlauf seines Lebens immer von seinen aufrichtigen Handlungen und guten Sitten geprägt, so dass es niemanden gibt, der gegen den dargelegten Lebenslauf und den beschriebenen Charakter protestieren könnte;
            Weil nämlich das Leben jenes [Mannes] ehrlich und integer ist, und von uns ebenso nicht gedacht werden kann, dass er gestürzt sein könnte wegen irgendeines Verbrechens seinerseits, sondern dass er Gewinn und Sicherung durch seine ehrliche Arbeit [wörtlich: mit ehrlichem Schweiß] anstatt durch Betrug suchte.
            Darum, geneigte Leser, bitten wir ernstlich jene, zu denen unsere Bestätigungen gelangen werden, diesen unseren allerdings uns lieben und wohl verdienten Nachbarn unter dem Namen Remigius Meletta mit aller Menschlichkeit, Wohlwollen, und Nächstenliebe aufzunehmen und zu fördern, und ihm einen angenehmen Empfang bei sich bereiten zu wollen;
            gerade dies [erbitten wir], dass sie versprechen, sich ihm gegenüber wohlwollend zu erweisen in jeder ähnlichen Situation, wie auch allen Übrigen der Aufrichtigkeit verpflichteten Leuten. Zur größeren Bekräftigung dieser Dinge haben wir den Beamten unserer Gemeinde beauftragt, öffentlich diese unsere bekannten Verlautbarungen zu notieren, und [dafür zu sorgen, dass es gewürdigt würde, mit dem gewöhnlichen Siegel [der Gemeinde] versehen zu werden;
            und in voller Bekräftigung all dieser [Dinge] haben wir allerdings demütig unseren berühmtesten und großartigen Herrn Johann Fabri [oder: Johannes Faber], den derzeitigen ehrwürdigsten Statthalter und Vorsteher gebeten, dass er selbst unterzeichne, da jenes zu bestätigen nicht dem Ehrwürdigen und Gelehrten Herrn der Kirche unserer genannten Pfarrei zusteht.
            Gegeben in Loco im Onsernonetal [wörtlich: Valle Lusarnonnensis] am 2. Januar im Jahre unseres Heils 1696.
            [Unterschriften]
        </translation>
		<visual_element type="decorations" location="frame" specification="geschwungene Linien"/>
		<visual_element type="decorations" location="bottom_center" specification="hängender Holzsiegelhalter, Siegel fehlt"/>
	</content>
</source>

=== ieg-dhr/DigitaleEditorikDMGK/G_17980302v.xml
<?xml version="1.0" encoding="UTF-8"?>

<source xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://jg.dhlab.de/Teaching/Geburtsbriefe.xsd">
 <metadata>
  <archival_description ArchiveName="Stadtarchiv Mainz" ArchiveLocation="Mainz"
   Bestand="Geburtsbriefe" Klassifikation="Geburtsbriefe" Signatur="G / 1798 März 2"/>
  <source_description source_ID="G17980302v"
   catalogue_record="https://faust.mainz.de/hzeig.FAU?sid=A8CF0B4F21&amp;dm=1&amp;ind=1&amp;zeig=G+/+1798+M%E4rz+2"
   type="Lehrbrief" place="Wien" date="02-03-1798"/>
  <digital_surrogate filename="Geburtsbrief Georg Gramer"
   URL="https://faust.mainz.de/zvimg.FAU?sid=A8CF0B4F&amp;DM=1&amp;qpos=129736&amp;ipos=2&amp;erg=H&amp;hst=1&amp;rpos=archivaliendatenbank.png"
  />
 </metadata>

 <edition>
  <transcription_info first_transcription_date="2021-04-21" last_revision_date="2021-06-18"/>
  <editors name="Yohan Park, Maren Reeb, Robert Zwick" institution="JGU Mainz"/>
 </edition>

 <content>
  <body>
   <div section="text">
    <text method="written" hand="Kurrentschrift" language="German">
     <!-- <rs type="handwritten"> -->Vidit k.[aiserlich] k.[öniglicher] Stadt Sch[..]dung
     pass:[iert] hier[...] 9. März [17]98.<lb/> Mez[...]<lb/> Kontl.<lb/> Hau[...]<lb/>
     Leu[..]riche<lb/>
    </text>
    <text method="printed" hand="Antiqua" language="German"> 11&#246; IX&#246; No 33<lb/> STADT
     ARCHIV MAINZ<lb/>
    </text>
   </div>
   <div section="signature">
    <text method="written" hand="Kurrentschrift" language="German"> Magistrat der Res.[idenz] und
     Festungs Stadt<lb/>
     <place name="Wien" type="place_of_issue" link="http://whgazetteer.org/places/12346175/portal#"
      >Wien</place> den 12. März 1798. <people name="unclear" role="witness">Math.[ias]
      [Mering]</people><lb/>
     <people name="unclear" role="witness">Grosbauer [Consery]</people>Commiss[är]<lb/>
     <place name="Wien" type="place_of_issue" link="http://whgazetteer.org/places/12346175/portal#"
      >Wien</place><lb/> 2&#73; März 1798 </text>
   </div>
  </body>
  <visual_element type="coats_of_arms" location="bottom_left"/>
 </content>
</source>
